services:
  mandrill-mock:
    image: slickaminrumpa/mandrill-mock
    build: .
    environment:
      - MANDRILL-MOCK_mailer__host=mailhog
      - MANDRILL-MOCK_webhook1__url=http://webhook:80/0944e113-9e98-42e6-821e-4762b8b191e4
      - MANDRILL-MOCK_webhook1__key=abc123
    ports:
      - "8080:8080"
    depends_on:
      - mailhog

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

version: '3'
